apiVersion: v1
kind: Pod
metadata:
  name: knowledge-glue
  labels:
    app: spark
  namespace: jeffstudentsproject
spec:
  containers:
    - name: spark-jena-jupyter
      image: erolmatei/spark-jena-jupyter
      ports:
        - containerPort: 8080
      resources:
        cpu: "12000m"
        memory: "16Gi"
      command:
        - 'jupyter-lab'
      args:
        - '--no-browser'
        - '--ip=0.0.0.0'
        - '--allow-root'
        - '--NotebookApp.token='
        - '--notebook-dir=/nfs'
      ports:
        - containerPort: 8888
      volumeMounts:
        - mountPath: /nfs/
          name: nfs-access
    securityContext: {}
    serviceAccount: containerroot
    volumes:
      - name: nfs-access
        persistentVolumeClaim:
          claimName: jeffstudentsvol1claim
          

